In [1]:
import numpy as np

# Classe Network

- Sizes se refere a o número de neurônios em cada camada, por exemplo 10 neurônios na camada de entrada, 5 neurônios na cada oculta e 1 neurônio na camada de saída

In [2]:
sizes = [10,5,1]

- A partir do número de neurônios em cada camada, gera-se bias aleatórios para as próximas camadas, menos para a camada de entrada
- Retorna-se portanto uma lista com vetores colunas com o número de linhas correspondendo ao número de neurônios das camadas ocultas e camada de saída se for o caso 

In [3]:
[np.random.randn(y, 1) for y in sizes[1:]]

[array([[ 0.56740227],
        [-0.6903982 ],
        [ 1.59747388],
        [-0.32919583],
        [-1.04324224]]),
 array([[-0.40940221]])]

### Geração dos pesos aleatórios

In [4]:
#Revisão sobre a função zip
x = [1,2,3]
y = [4,5,6]
list(zip(x,y))

[(1, 4), (2, 5), (3, 6)]

- Retornar o número de pesos que deverá ser gerado através da função zip 

In [5]:
sizes[:-1]

[10, 5]

In [6]:
sizes[1:]

[5, 1]

In [7]:
list(zip(sizes[:-1], sizes[1:]))

[(10, 5), (5, 1)]

- Os pesos aleatórios são gerados da mesma maneira com o bias, ou seja, com a função np.random.randn
- Observa-se que é retornado uma lista com dois arrays. 
- O primeiro array corresponde aos pesos que ligam os neurônios da camada de entrada com a primeira camada oculta 
- O segundo array corrresponde aos pesos que conectam os neurônios da primeira camada oculta com a camada de saída

In [8]:
[np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]

[array([[-9.95584639e-01, -1.28647067e+00, -1.00279245e+00,
         -9.86279603e-01, -9.30594054e-01,  1.31278636e+00,
          1.36674210e+00, -7.71964187e-01,  4.88449401e-01,
         -3.64712806e-01],
        [ 6.46234377e-01,  5.52698371e-01,  1.09710355e+00,
          6.26418785e-01, -1.40184271e-01, -6.85146583e-01,
          1.23420769e+00,  7.04152079e-01,  6.47084371e-01,
          3.29033006e-01],
        [-1.73838955e+00,  2.68687682e+00, -1.26052685e+00,
          3.96686410e-01,  1.51464039e+00, -1.22617556e-03,
          1.38775556e+00,  4.74477055e-01,  1.81787721e+00,
         -3.62233195e-01],
        [ 9.91781472e-01,  2.96412351e-02,  4.77657279e-01,
         -1.23482647e-01, -1.90344246e-01,  4.54598585e-01,
          1.87031774e+00,  6.08605161e-01,  7.03805443e-01,
          1.43796753e+00],
        [ 1.06780198e+00, -3.48763931e-01,  9.15213793e-01,
         -1.36376719e-01, -1.14176901e+00,  3.80734247e-01,
         -5.44194159e-01, -8.75200739e-01,  5.856175

In [9]:
class Network(object):
    
    #sizes do tipo lista
    def __init__(self, sizes):
        
        #Passando os atributos da rede neural
        #Número de camadas da rede neural
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes [1:]]
        self.weights = [np.random.randn(y, x) for x,y in zip(sizes[:-1], sizes[1:])]
    
    

#### Pode-se criar um objeto a partir da classe Network e têm-se assim uma arquitetura de rede neural 

In [10]:
nn = Network(sizes=[10,5,1])

In [11]:
nn.num_layers

3

In [12]:
nn.sizes

[10, 5, 1]

In [13]:
nn.biases

[array([[-1.71268758],
        [-0.28836017],
        [ 0.07047816],
        [ 0.0120389 ],
        [ 1.09606926]]),
 array([[-0.52837378]])]

In [14]:
nn.weights

[array([[ 1.63011454,  0.18660848, -1.63335205,  0.48949745, -1.25851588,
         -0.43232617, -0.08534341,  0.3607494 , -0.85260924, -0.31139361],
        [ 0.29092307,  0.71216018,  0.48116471, -2.15349388,  0.99175812,
         -0.09601449, -1.10323191, -0.16099279,  0.34594325, -0.43996206],
        [ 0.62994886, -2.28868755, -0.01086047,  2.02129198,  0.46175618,
          1.57588828, -0.76000119, -0.03564152,  0.09346019,  0.40169615],
        [-0.4882501 ,  0.44477911, -0.84535334, -0.3517151 , -0.40339094,
         -0.71510277, -0.90129742,  2.68919292,  2.22622224, -0.32973476],
        [ 1.03817395,  1.35295996,  0.20346065,  0.71744204, -0.65504615,
          0.09260409, -1.20844556,  1.35632491,  1.20974323,  0.3435035 ]]),
 array([[-0.36903966, -0.95083264,  0.5989238 ,  0.24018454,  0.30277209]])]

# Função de ativação

- A função de ativação irá ser aplicada sobre: (W*A + b)
- Em que:
- W: Matriz dos pesos
- A: Matriz de entradas
- b: Vetor de bias

- 'z' é uma entrada do tipo vetor ou matriz numpy, mas o numpy aplica automaticamente a função sigmoide de forma elementwise, isto é, na for vetorizada 

In [15]:
def sigmoid(z):
    return 1.0/(1.0 + np.exp(-z))

# FeedForward
- Função feedforward será responsável por dada uma entrada, retornar uma saída, após a aplicação das funções de multiplicação, soma e função de ativação

In [16]:
#Revisãozinha np.dot
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
adot = np.dot(a1,a2)
print(a1,a2,adot)

[1 2 3] [4 5 6] 32


(Repetindo o código para fins didático né)

In [17]:
class Network(object):
    
    #sizes do tipo lista
    def __init__(self, sizes):
        
        #Passando os atributos da rede neural
        #Número de camadas da rede neural
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes [1:]]
        self.weights = [np.random.randn(y, x) for x,y in zip(sizes[:-1], sizes[1:])]
    
    #São realizadas operações sobre a entrada a retorna-se a apóes estas operações
    def feedforward(self, a):
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w,a)+b) #Tá criada em algum lugar do notebook
        return a 
        

# Stochastic Gradient Descent

- Visualização de como através da função range obtêm-se os mini_batches
- Deve-se notar que na função, antes da aplicação da função range, os dados foram embaralhados através da função random.shuffle(data)

In [18]:
#Para dar prints horizontais
%pprint

Pretty printing has been turned OFF


In [19]:
list(range(0,1000,32))

[0, 32, 64, 96, 128, 160, 192, 224, 256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992]

In [21]:
class Network(object):
    
    #sizes do tipo lista
    def __init__(self, sizes):
        
        #Passando os atributos da rede neural
        #Número de camadas da rede neural
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes [1:]]
        self.weights = [np.random.randn(y, x) for x,y in zip(sizes[:-1], sizes[1:])]
    
    #São realizadas operações sobre a entrada a retorna-se a apóes estas operações
    def feedforward(self, a):
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w,a)+b) #Tá criada em algum lugar do notebook
        return a 
        
    def SGD(self, training_data, epochs, mini_batch_size, eta, test_data = None):
        # Este tratamento que retorna o tamanho da base de dados de teste será útil no batch_size
        training_data = list(training_data)
        n = len(training_data)
        
        if test_data:
            test_data = list(test_data)
            n_test = len(test_data)
        
        #Batch_size, ou seja, conjunto de dados que serão utilizados em capa época para a atualização dos pesos
        for j in range(epochs):
            random.shuffle(training_data)
            #Retornar o conjunto de dados mini_batches a partir do tamanho do batch passado através da variável mini_batch_size
            mini_batches = [training_data[k:k+mini_batch_size] for k in range(0,n,mini_batch_size)]
            
            #eta é a taxa de aprendizagem 
            for mini_batch in mini_batches:
                #Chamando o método update_mini_batch desta classe
                self.update_mini_batch(mini_batch, eta)
                
            #Se os dados de testes forem passados, será impresso uma linha com a avaliação do modelo nestes dados de teste em cada época
            if test_data:
                #Chamando o método evaluate desta classe
                print("Epoch {} : {} / {}".format(j,self.evaluate(test_data),n_test))
            else:
                print("Epoch {} finalizada".format(j))
    
        
        
        

## Função update_mini_batch
- Nabla ($\nabla$) ou (del) é a letra que representa o gradiente em cálculo vetorial

- Inicialização dos vetores que receberão os gradientes do bias e gradientes dos pesos

In [24]:
#Gradiente para a atualização dos bias:
nabla_b = [np.zeros(b.shape) for b in nn.biases]; nabla_b

[array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]]), array([[0.]])]

In [25]:
nabla_w = [np.zeros(w.shape) for w in nn.weights]; nabla_w

[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), array([[0., 0., 0., 0., 0.]])]

- Sabemos que mini_batch é uma tupla, porque training_data é um tupla
- Esta tupla é constutuída por (x,y), ou seja, os dados de entrada e dados de saída

### Antes de mostrar a função update_mini_batch, é interessante mostrar a principal função de todas na atualização dos pesos, ou seja, a self.backprop

In [31]:
def backprop(self, x, y):
    
    #Gradientes dos biases e dos pesos
    nabla_b = [np.zeros(b.shape) for b in self.biases]
    nabla_w = [np.zeros(w.shape) for w in self.weights]
    
    #FeedForward (Desta maneira posso trabalhar com uma única função de ativação em todas camadas? )
    activation = x
    
    #Lista com todas ativações, de camada por camada, para chamar depois
    activations = [x]
    
    #Lista que armazena os vetores z, camada por camada
    zs = []
    
    for b, w in zip(self.biases, self.weights):
            
        z = np.dot(w, activation) + b
        zs.append(z)
        activation = sigmoid(z)
        activations.append(activation)
        
    #Backward passa
    #Função cost_derivative recebe como parâmetros a função de ativação do nó e a saída do nó (esta seria só a camada de saaída ou todas?)
    #Porque y seria a saída não? 
    #Sigmoid prime é outra função que retorna o valor da derivada no ponto?
    #Se estamos trabalhando com [-1], está se referindo aos últimos valores dos vetores, logo camada de saída? 
    delta = self.cost_derivative(activations[-1],y) * sigmoid_prime(zs[-1])
    nabla_b[-1] = delta
    nabla_w[-1] = np.dot(delta, activations[-2].transpose())
    
    #Para cada camada:
    for l in range(2, self.num_layers):
        z = zs[-l]
        sp = sigmoide_prime(z)
        
        #Este produto que retorna delta a partir da multiplicação com delta é o :
        #DeltaCamada1 = pesos*DeltaCamada2 (Camada2 pode ser a camada de saída e Camada 1 a camada oculta, por exemplo)
        delta = np.dot(self.weights[-l+1].transpose(), delta)*sp
        nabla_b[-l] = delta
        nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
        
    #Retorna os dois gradientes
    return (nabla_b, nabla_w)

### Agora que sabemos como funciona o método BackProp que será uitlizado no método update_mini_batch, podemos voltar para a função principal
(Repetindo todo algoritmo por questões didáticas)

In [35]:
class Network(object):
    
    #Sizes é um objeto do tipo lista, com o número de camadas da rede
    #Aqui definimos os atributos da arquitetura da rede
    def __init__(self, sizes):
        
        #Passando os atributos da rede neural
        #Número de camadas da rede neural
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes [1:]]
        self.weights = [np.random.randn(y, x) for x,y in zip(sizes[:-1], sizes[1:])]
    
    #São realizadas operações sobre a entrada a retorna-se 'a' após estas operações
    def feedforward(self, a):
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w,a)+b) #Função sigmoid está presente no final desta classe
        return a 
        
    def SGD(self, training_data, epochs, mini_batch_size, eta, test_data = None):
        # Este tratamento que retorna o tamanho da base de dados de teste será útil no batch_size
        training_data = list(training_data)
        n = len(training_data)
        
        if test_data:
            test_data = list(test_data)
            n_test = len(test_data)
        
        #Batch_size, ou seja, conjunto de dados que serão utilizados em capa época para a atualização dos pesos
        for j in range(epochs):
            random.shuffle(training_data)
            #Retornar o conjunto de dados mini_batches a partir do tamanho do batch passado através da variável mini_batch_size
            mini_batches = [training_data[k:k+mini_batch_size] for k in range(0,n,mini_batch_size)]
            
            #eta é a taxa de aprendizagem 
            for mini_batch in mini_batches:
                #Chamando o método update_mini_batch desta classe
                self.update_mini_batch(mini_batch, eta)
                
            #Se os dados de testes forem passados, será impresso uma linha com a avaliação do modelo nestes dados de teste em cada época
            if test_data:
                #Chamando o método evaluate desta classe
                print("Epoch {} : {} / {}".format(j,self.evaluate(test_data),n_test))
            else:
                print("Epoch {} finalizada".format(j))
    
    def update_mini_batch(self, mini_batch, eta):
            
        nabla_b = [np.zteros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]
            
        for x, y in mini_batch:
            delta_nabla_b, delta_nabla_w = self.backprop(x,y)
            nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
            nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]

        #############################################################################################################
        #Atualização dos pesos efetivamente ocorre aqui!
        self.weights = [w-(eta/len(mini_batch))*nw for w, nw in zip(self.weights, nabla_w)]
        self.biases = [b-(eta/len(mini_batch))*nb for b, nb in zip(self.biases, nabla_b)]            
        ##############################################################################################################
        
                
    # O método backprop é responsável por receber todos os valores iniciais dos nós, tanto os nós de entrada e
    # os valores de nós aleatórios de saída
    # A Função backprop faz uso de outras funções como sigmoid para retornar o valor da aplicação da sigmoid na multiplicação pesos*nós + bias
    # Também faz uso da função cost_derivative que traz a diferença entre a saída real e o valor predito? 
    # ALém de utilizar a função sigmoide_prime que retorna a derivada no nó da função sigmoid 
    def backprop(self, x, y):
    
        #Gradientes dos biases e dos pesos
        nabla_b = [np.zeros(b.shape) for b in self.biases]
        nabla_w = [np.zeros(w.shape) for w in self.weights]

        #FeedForward (Desta maneira posso trabalhar com uma única função de ativação em todas camadas? )
        #Este valor na realidade no início são os valores dos próprios nós não? 
        #Depois aplica-se a função sigmoide sobre o valor de activation
        activation = x

        #Lista com todas ativações, de camada por camada, para chamar depois
        activations = [x]

        #Lista que armazena os vetores z, camada por camada
        zs = []
        
        #Este loop é responsável por retornar todas as ativações, ou seja, todos os valores dos nós
        # É efetivamente o Forward Pass, em que a primeira activation é a entrada da rede, os nós de entrada, e ao final
        # na última camada do activations têm-se os nós da saída
        for b, w in zip(self.biases, self.weights):
            z = np.dot(w, activation) + b
            zs.append(z)
            activation = sigmoid(z)
            activations.append(activation)

        #Backward pass
        #Função cost_derivative recebe como parâmetros a função de ativação do nó e a saída do nó (esta seria só a camada de saaída ou todas?)
        #Porque y seria a saída não? 
        #Sigmoid prime é outra função que retorna o valor da derivada no ponto?
        #Se estamos trabalhando com [-1], está se referindo aos últimos valores dos vetores, logo camada de saída? 
        delta = self.cost_derivative(activations[-1],y) * sigmoid_prime(zs[-1]) #DeltaOutput da saída. (Erro*Derivada)
        nabla_b[-1] = delta 
        nabla_w[-1] = np.dot(delta, activations[-2].transpose()) #DeltaHidden: DeltaOutput*NósDaÚltimaCamadaOculta

        #Para cada camada depois de recebidos os gradientes respectivos à última camada
        for l in range(2, self.num_layers):
            z = zs[-l] #l-ésimo última camada
            sp = sigmoide_prime(z) #Derivada do valor do nó

            #Este produto que retorna delta a partir da multiplicação com delta é o :
            #DeltaCamada1 = pesos*DeltaCamada2 (Camada2 pode ser a camada de saída e Camada 1 a camada oculta, por exemplo)
            delta = np.dot(self.weights[-l+1].transpose(), delta)*sp
            nabla_b[-l] = delta
            nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())

        #Retorna os dois gradientes para todos os biases e todos os pesos
        return (nabla_b, nabla_w)
                
    #Avaliar o resultado da rede com dados de teste, se estes forem passados
    def evaluate(self, test_data):
        test_results = [(np.argmax(self.feedforward(x)),y) for (x,y) in test_data]
        return sum(int(x == y) for (x,y) in test_results)
    
    def cost_derivative(self, output_activations, y):
        return (output_activations-y)
    
    def sigmoid(z):
        return 1.0/(1.0+np.exp(-z))
    
    #Primitiva da sigmoid
    def sigmoid_prime(z):
        return sigmoid(z)*(1-sigmoid(z))

            