In [45]:
import numpy as np

# Classe Network

- Sizes se refere a o número de neurônios em cada camada, por exemplo 10 neurônios na camada de entrada, 5 neurônios na cada oculta e 1 neurônio na camada de saída

In [46]:
sizes = [10,5,1]

- A partir do número de neurônios em cada camada, gera-se bias aleatórios para as próximas camadas, menos para a camada de entrada
- Retorna-se portanto uma lista com vetores colunas com o número de linhas correspondendo ao número de neurônios das camadas ocultas e camada de saída se for o caso 

In [47]:
[np.random.randn(y, 1) for y in sizes[1:]]

[array([[ 0.32887234],
        [ 2.36531583],
        [-0.57845184],
        [-3.19790401],
        [-0.61438943]]),
 array([[-0.36100466]])]

### Geração dos pesos aleatórios

In [48]:
#Revisão sobre a função zip
x = [1,2,3]
y = [4,5,6]
list(zip(x,y))

[(1, 4), (2, 5), (3, 6)]

- Retornar o número de pesos que deverá ser gerado através da função zip 

In [49]:
sizes[:-1]

[10, 5]

In [50]:
sizes[1:]

[5, 1]

In [51]:
list(zip(sizes[:-1], sizes[1:]))

[(10, 5), (5, 1)]

- Os pesos aleatórios são gerados da mesma maneira com o bias, ou seja, com a função np.random.randn
- Observa-se que é retornado uma lista com dois arrays. 
- O primeiro array corresponde aos pesos que ligam os neurônios da camada de entrada com a primeira camada oculta 
- O segundo array corrresponde aos pesos que conectam os neurônios da primeira camada oculta com a camada de saída

In [52]:
[np.random.randn(y, x) for x, y in zip(sizes[:-1], sizes[1:])]

[array([[-0.68138786,  0.04389685, -1.10463541, -0.2462504 , -0.49491797,
         -0.27663941, -0.12200739,  0.58699268,  1.0484374 , -2.09943768],
        [-0.19081019, -0.93693968,  0.23389491, -1.14955355,  0.1847655 ,
         -0.94389823,  0.54575563,  0.92201794,  0.16003407,  1.98654868],
        [-0.88940788,  0.50941556, -1.03462   , -0.10449545, -0.84407084,
         -0.43773836, -2.25029955,  0.07508225,  0.12530092,  0.63388036],
        [-0.08152339,  0.90839921, -0.57334633,  0.08802887,  0.85222504,
         -0.0899894 , -1.40756457,  0.22310411,  0.42970818, -0.95855779],
        [-2.3164256 , -0.06641736, -0.92567138,  1.00323651, -0.42699385,
         -0.17217081,  1.96123758,  1.24773313, -0.0602561 ,  0.35067418]]),
 array([[ 0.07498877,  1.97676829, -1.14874596,  0.14662194, -0.7974334 ]])]

In [53]:
class Network(object):
    
    #sizes do tipo lista
    def __init__(self, sizes):
        
        #Passando os atributos da rede neural
        #Número de camadas da rede neural
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes [1:]]
        self.weights = [np.random.randn(y, x) for x,y in zip(sizes[:-1], sizes[1:])]
    
    

#### Pode-se criar um objeto a partir da classe Network e têm-se assim uma arquitetura de rede neural 

In [54]:
nn = Network(sizes=[10,5,1])

In [55]:
nn.num_layers

3

In [56]:
nn.sizes

[10, 5, 1]

In [57]:
nn.biases

[array([[-0.28266738],
        [ 0.2002924 ],
        [-2.03424764],
        [-1.059309  ],
        [ 1.63589831]]),
 array([[0.12465653]])]

In [58]:
nn.weights

[array([[ 0.52018611, -0.49992298, -0.42774913, -0.55542977, -0.08335698,
          0.79057802,  0.32757228,  1.44698662, -1.7144653 ,  0.32907682],
        [ 0.13605404,  1.66132161,  0.0373024 , -1.21890293, -0.24245149,
         -0.09326167,  0.06433936,  0.59675575, -1.67971082, -0.07696922],
        [-0.19407594, -0.75720441,  1.00154544,  0.19298743,  0.99193949,
          0.19240572,  0.83562101,  0.54713698, -0.79066446,  0.37924776],
        [-0.43887663, -0.86591332, -0.31110745, -1.33516429,  0.16270157,
         -1.62459603, -0.0241579 ,  1.1076185 ,  0.2977608 ,  0.49779011],
        [ 0.33085176, -0.79464027,  1.90571557,  1.73573952, -0.22362687,
          0.08590715,  1.32451449, -0.44971274, -0.12769807,  1.06357673]]),
 array([[ 0.25630611, -1.40427864, -0.91358507,  3.21828838, -0.24869094]])]

# Função de ativação

- A função de ativação irá ser aplicada sobre: (W*A + b)
- Em que:
- W: Matriz dos pesos
- A: Matriz de entradas
- b: Vetor de bias

- 'z' é uma entrada do tipo vetor ou matriz numpy, mas o numpy aplica automaticamente a função sigmoide de forma elementwise, isto é, na for vetorizada 

In [59]:
def sigmoid(z):
    return 1.0/(1.0 + np.exp(-z))

# FeedForward
- Função feedforward será responsável por dada uma entrada, retornar uma saída, após a aplicação das funções de multiplicação, soma e função de ativação

In [66]:
#Revisãozinha np.dot
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
adot = np.dot(a1,a2)
print(a1,a2,adot)

[1 2 3] [4 5 6] 32


(Repetindo o código para fins didático né)

In [67]:
class Network(object):
    
    #sizes do tipo lista
    def __init__(self, sizes):
        
        #Passando os atributos da rede neural
        #Número de camadas da rede neural
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes [1:]]
        self.weights = [np.random.randn(y, x) for x,y in zip(sizes[:-1], sizes[1:])]
    
    #São realizadas operações sobre a entrada a retorna-se a apóes estas operações
    def feedforward(self, a):
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w,a)+b) #Tá criada em algum lugar do notebook
        return a 
        

# Stochastic Gradient Descent

- Visualização de como através da função range obtêm-se os mini_batches
- Deve-se notar que na função, antes da aplicação da função range, os dados foram embaralhados através da função random.shuffle(data)

In [77]:
#Para dar prints horizontais
%pprint

Pretty printing has been turned OFF


In [78]:
list(range(0,1000,32))

[0, 32, 64, 96, 128, 160, 192, 224, 256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992]

In [88]:
class Network(object):
    
    #sizes do tipo lista
    def __init__(self, sizes):
        
        #Passando os atributos da rede neural
        #Número de camadas da rede neural
        self.num_layers = len(sizes)
        self.sizes = sizes
        self.biases = [np.random.randn(y, 1) for y in sizes [1:]]
        self.weights = [np.random.randn(y, x) for x,y in zip(sizes[:-1], sizes[1:])]
    
    #São realizadas operações sobre a entrada a retorna-se a apóes estas operações
    def feedforward(self, a):
        for b, w in zip(self.biases, self.weights):
            a = sigmoid(np.dot(w,a)+b) #Tá criada em algum lugar do notebook
        return a 
        
    def SGD(self, training_data, epochs, mini_batch_size, eta, test_data = None):
        # Este tratamento que retorna o tamanho da base de dados de teste será útil no batch_size
        training_data = list(training_data)
        n = len(training_data)
        
        if test_data:
            test_data = list(test_data)
            n_test = len(test_data)
        
        #Batch_size, ou seja, conjunto de dados que serão utilizados em capa época para a atualização dos pesos
        for j in range(epochs):
            random.shuffle(training_data)
            #Retornar o conjunto de dados mini_batches a partir do tamanho do batch passado através da variável mini_batch_size
            mini_batches = [training_data[k:k+mini_batch_size] for k in range(0,n,mini_batch_size)]
            
            #eta é a taxa de aprendizagem 
            for mini_batch in mini_batches:
                #Chamando o método update_mini_batch desta classe
                self.update_mini_batch(mini_batch, eta)
                
            #Se os dados de testes forem passados, será impresso uma linha com a avaliação do modelo nestes dados de teste em cada época
            if test_data:
                #Chamando o método evaluate desta classe
                print("Epoch {} : {} / {}".format(j,self.evaluate(test_data),n_test))
            else:
                print("Epoch {} finalizada".format(j))
    
    def update_mini_batch(self, mini_batch, eta):
        
        